#!/bin/bash
# Build a fully inline version of the app for maximum Kindle compatibility
# This embeds ALL JavaScript directly into the HTML file

echo "Building inline version for Kindle..."

# Create backup
cp index.html index-original-backup.html
echo "✓ Backed up index.html to index-original-backup.html"

# Read the JavaScript files
POLYFILLS=$(cat polyfills.js)
CONFIG=$(cat config.js)
APP=$(cat app.js)

# Create inline HTML
cat > index-inline.html << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="color-scheme" content="light">
    <title>Lichess - Kindle</title>
    <link rel="icon" type="image/svg+xml" href="favicon.svg">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="app">
        <!-- Loading Screen -->
        <div id="screen-loading" class="screen">
            <h1>♔ Lichess</h1>
            <p class="subtitle">Loading...</p>
            <div id="debug-log" class="debug-log"></div>
        </div>

        <!-- Error Display -->
        <div id="error-banner" class="error-banner hidden">
            <span id="error-message"></span>
            <button id="btn-dismiss-error" class="btn btn-small">×</button>
        </div>

        <!-- Login Screen -->
        <div id="screen-login" class="screen hidden">
            <h1>♔ Lichess</h1>
            <p class="subtitle">Kindle Edition</p>
            <button id="btn-login" class="btn btn-large">Login with Lichess</button>
            <p class="help-text">You'll be redirected to Lichess to authorize this app.</p>
        </div>

        <!-- Lobby Screen -->
        <div id="screen-lobby" class="screen hidden">
            <header>
                <span id="username">Player</span>
                <button id="btn-logout" class="btn btn-small">Logout</button>
            </header>

            <h2>New Game</h2>

            <div id="time-controls">
                <!-- Time control buttons generated by JS -->
            </div>

            <div id="seeking" class="hidden">
                <p>Seeking opponent...</p>
                <button id="btn-cancel-seek" class="btn">Cancel</button>
            </div>

            <div id="ongoing-games" class="hidden">
                <h3>Ongoing Games</h3>
                <div id="games-list"></div>
            </div>
        </div>

        <!-- Game Screen -->
        <div id="screen-game" class="screen hidden">
            <header class="game-header">
                <button id="btn-back" class="btn btn-small">← Back</button>
                <span id="game-status">Playing</span>
            </header>

            <div class="player-info opponent">
                <span id="opponent-name">Opponent</span>
                <span id="opponent-clock" class="clock">--:--</span>
            </div>

            <div id="board">
                <!-- 8x8 board generated by JS -->
            </div>

            <div class="player-info player">
                <span id="player-name">You</span>
                <span id="player-clock" class="clock">--:--</span>
            </div>

            <div id="game-controls">
                <button id="btn-resign" class="btn">Resign</button>
                <button id="btn-draw" class="btn">Offer Draw</button>
            </div>

            <div id="game-result" class="hidden">
                <p id="result-text"></p>
                <button id="btn-new-game" class="btn btn-large">New Game</button>
            </div>

            <div id="promotion-modal" class="modal hidden">
                <div class="modal-content">
                    <p>Promote to:</p>
                    <div class="promotion-pieces">
                        <button class="promo-btn" data-piece="q">♛</button>
                        <button class="promo-btn" data-piece="r">♜</button>
                        <button class="promo-btn" data-piece="b">♝</button>
                        <button class="promo-btn" data-piece="n">♞</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ALL CODE INLINE -->
    <script>
HTMLEOF

# Append polyfills
echo "$POLYFILLS" >> index-inline.html

# Append config
echo "$CONFIG" >> index-inline.html

# Append app
echo "$APP" >> index-inline.html

# Close script and HTML tags
cat >> index-inline.html << 'HTMLEOF'
    </script>
</body>
</html>
HTMLEOF

echo "✓ Created index-inline.html with all JS embedded"
echo ""
echo "To use the inline version:"
echo "  1. Test it: open index-inline.html in browser"
echo "  2. Deploy it: mv index-inline.html index.html"
echo "  3. Commit: git add index.html && git commit -m 'Use inline JS for Kindle'"
echo ""
echo "File sizes:"
ls -lh index*.html
