#!/bin/bash
# Build complete Lichess app in single HTML file with working debug logger

echo "Building full app..."

cat > index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="color-scheme" content="light">
    <title>Lichess - Kindle</title>
    <link rel="icon" type="image/svg+xml" href="favicon.svg">
    <style>
EOF

# Inline CSS
cat style.css >> index.html

cat >> index.html << 'EOF'
    </style>
</head>
<body>
    <div id="app">
        <!-- Loading Screen -->
        <div id="screen-loading" class="screen">
            <h1>♔ Lichess</h1>
            <p class="subtitle">Loading...</p>
            <div id="debug-log" class="debug-log"></div>
        </div>

        <!-- Error Display -->
        <div id="error-banner" class="error-banner hidden">
            <span id="error-message"></span>
            <button id="btn-dismiss-error" class="btn btn-small">×</button>
        </div>

        <!-- Login Screen -->
        <div id="screen-login" class="screen hidden">
            <h1>♔ Lichess</h1>
            <p class="subtitle">Kindle Edition</p>
            <button id="btn-login" class="btn btn-large">Login with Lichess</button>
            <p class="help-text">You'll be redirected to Lichess to authorize this app.</p>
        </div>

        <!-- Lobby Screen -->
        <div id="screen-lobby" class="screen hidden">
            <header>
                <span id="username">Player</span>
                <button id="btn-logout" class="btn btn-small">Logout</button>
            </header>

            <h2>New Game</h2>

            <div id="time-controls">
                <!-- Time control buttons generated by JS -->
            </div>

            <div id="seeking" class="hidden">
                <p>Seeking opponent...</p>
                <button id="btn-cancel-seek" class="btn">Cancel</button>
            </div>

            <div id="ongoing-games" class="hidden">
                <h3>Ongoing Games</h3>
                <div id="games-list"></div>
            </div>
        </div>

        <!-- Game Screen -->
        <div id="screen-game" class="screen hidden">
            <header class="game-header">
                <button id="btn-back" class="btn btn-small">← Back</button>
                <span id="game-status">Playing</span>
            </header>

            <div class="player-info opponent">
                <span id="opponent-name">Opponent</span>
                <span id="opponent-clock" class="clock">--:--</span>
            </div>

            <div id="board">
                <!-- 8x8 board generated by JS -->
            </div>

            <div class="player-info player">
                <span id="player-name">You</span>
                <span id="player-clock" class="clock">--:--</span>
            </div>

            <div id="game-controls">
                <button id="btn-resign" class="btn">Resign</button>
                <button id="btn-draw" class="btn">Offer Draw</button>
            </div>

            <div id="game-result" class="hidden">
                <p id="result-text"></p>
                <button id="btn-new-game" class="btn btn-large">New Game</button>
            </div>

            <div id="promotion-modal" class="modal hidden">
                <div class="modal-content">
                    <p>Promote to:</p>
                    <div class="promotion-pieces">
                        <button class="promo-btn" data-piece="q">♛</button>
                        <button class="promo-btn" data-piece="r">♜</button>
                        <button class="promo-btn" data-piece="b">♝</button>
                        <button class="promo-btn" data-piece="n">♞</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
// Working debug logger from test version
(function() {
    var debugDiv = document.getElementById('debug-log');
    var logs = [];
    var logCount = 0;
    var maxLogs = 50;

    window.simpleLog = function(msg, isError) {
        logCount++;
        var time = new Date().toLocaleTimeString();
        var text = logCount + '. [' + time + '] ' + msg;
        logs.push({ text: text, isError: isError });

        if (logs.length > maxLogs) {
            logs.shift();
        }

        if (debugDiv) {
            var html = '';
            for (var i = 0; i < logs.length; i++) {
                var cls = logs[i].isError ? 'debug-line error' : 'debug-line';
                html += '<div class="' + cls + '">' + logs[i].text + '</div>';
            }
            debugDiv.innerHTML = html;
            debugDiv.scrollTop = debugDiv.scrollHeight;
        }
    };

    window.onerror = function(msg, url, line) {
        simpleLog('ERROR: ' + msg + ' at line ' + line, true);
        return true;
    };

    simpleLog('App starting...');
})();

// === POLYFILLS ===
EOF

# Add polyfills
cat polyfills.js >> index.html

cat >> index.html << 'EOF'

// === CONFIG ===
EOF

# Add config
cat config.js >> index.html

cat >> index.html << 'EOF'

// === APP ===
// Replace console.log with simpleLog
EOF

# Add app.js but replace the debug logger section
sed '/^\/\/ ============================================$/,/^console\.log = function/d' app.js | \
sed 's/console\.log(/simpleLog(/g' | \
sed 's/console\.error(/simpleLog(/g' | \
sed 's/console\.warn(/simpleLog(/g' >> index.html

cat >> index.html << 'EOF'
    </script>
</body>
</html>
EOF

echo "✓ Built index.html with full Lichess app"
ls -lh index.html
wc -l index.html
